# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Metric/~create/$",
        view=views.MetricCreateView.as_view(),
        name='Metric_create',
    ),
    url(
        regex="^Metric/(?P<pk>\d+)/~delete/$",
        view=views.MetricDeleteView.as_view(),
        name='Metric_delete',
    ),
    url(
        regex="^Metric/(?P<pk>\d+)/$",
        view=views.MetricDetailView.as_view(),
        name='Metric_detail',
    ),
    url(
        regex="^Metric/(?P<pk>\d+)/~update/$",
        view=views.MetricUpdateView.as_view(),
        name='Metric_update',
    ),
    url(
        regex="^Metric/$",
        view=views.MetricListView.as_view(),
        name='Metric_list',
    ),
	url(
        regex="^AbstractMetric/~create/$",
        view=views.AbstractMetricCreateView.as_view(),
        name='AbstractMetric_create',
    ),
    url(
        regex="^AbstractMetric/(?P<pk>\d+)/~delete/$",
        view=views.AbstractMetricDeleteView.as_view(),
        name='AbstractMetric_delete',
    ),
    url(
        regex="^AbstractMetric/(?P<pk>\d+)/$",
        view=views.AbstractMetricDetailView.as_view(),
        name='AbstractMetric_detail',
    ),
    url(
        regex="^AbstractMetric/(?P<pk>\d+)/~update/$",
        view=views.AbstractMetricUpdateView.as_view(),
        name='AbstractMetric_update',
    ),
    url(
        regex="^AbstractMetric/$",
        view=views.AbstractMetricListView.as_view(),
        name='AbstractMetric_list',
    ),
	url(
        regex="^DayMetric/~create/$",
        view=views.DayMetricCreateView.as_view(),
        name='DayMetric_create',
    ),
    url(
        regex="^DayMetric/(?P<pk>\d+)/~delete/$",
        view=views.DayMetricDeleteView.as_view(),
        name='DayMetric_delete',
    ),
    url(
        regex="^DayMetric/(?P<pk>\d+)/$",
        view=views.DayMetricDetailView.as_view(),
        name='DayMetric_detail',
    ),
    url(
        regex="^DayMetric/(?P<pk>\d+)/~update/$",
        view=views.DayMetricUpdateView.as_view(),
        name='DayMetric_update',
    ),
    url(
        regex="^DayMetric/$",
        view=views.DayMetricListView.as_view(),
        name='DayMetric_list',
    ),
	url(
        regex="^WeekMetric/~create/$",
        view=views.WeekMetricCreateView.as_view(),
        name='WeekMetric_create',
    ),
    url(
        regex="^WeekMetric/(?P<pk>\d+)/~delete/$",
        view=views.WeekMetricDeleteView.as_view(),
        name='WeekMetric_delete',
    ),
    url(
        regex="^WeekMetric/(?P<pk>\d+)/$",
        view=views.WeekMetricDetailView.as_view(),
        name='WeekMetric_detail',
    ),
    url(
        regex="^WeekMetric/(?P<pk>\d+)/~update/$",
        view=views.WeekMetricUpdateView.as_view(),
        name='WeekMetric_update',
    ),
    url(
        regex="^WeekMetric/$",
        view=views.WeekMetricListView.as_view(),
        name='WeekMetric_list',
    ),
	url(
        regex="^MonthMetric/~create/$",
        view=views.MonthMetricCreateView.as_view(),
        name='MonthMetric_create',
    ),
    url(
        regex="^MonthMetric/(?P<pk>\d+)/~delete/$",
        view=views.MonthMetricDeleteView.as_view(),
        name='MonthMetric_delete',
    ),
    url(
        regex="^MonthMetric/(?P<pk>\d+)/$",
        view=views.MonthMetricDetailView.as_view(),
        name='MonthMetric_detail',
    ),
    url(
        regex="^MonthMetric/(?P<pk>\d+)/~update/$",
        view=views.MonthMetricUpdateView.as_view(),
        name='MonthMetric_update',
    ),
    url(
        regex="^MonthMetric/$",
        view=views.MonthMetricListView.as_view(),
        name='MonthMetric_list',
    ),
	url(
        regex="^QuarterMetric/~create/$",
        view=views.QuarterMetricCreateView.as_view(),
        name='QuarterMetric_create',
    ),
    url(
        regex="^QuarterMetric/(?P<pk>\d+)/~delete/$",
        view=views.QuarterMetricDeleteView.as_view(),
        name='QuarterMetric_delete',
    ),
    url(
        regex="^QuarterMetric/(?P<pk>\d+)/$",
        view=views.QuarterMetricDetailView.as_view(),
        name='QuarterMetric_detail',
    ),
    url(
        regex="^QuarterMetric/(?P<pk>\d+)/~update/$",
        view=views.QuarterMetricUpdateView.as_view(),
        name='QuarterMetric_update',
    ),
    url(
        regex="^QuarterMetric/$",
        view=views.QuarterMetricListView.as_view(),
        name='QuarterMetric_list',
    ),
	url(
        regex="^YearMetric/~create/$",
        view=views.YearMetricCreateView.as_view(),
        name='YearMetric_create',
    ),
    url(
        regex="^YearMetric/(?P<pk>\d+)/~delete/$",
        view=views.YearMetricDeleteView.as_view(),
        name='YearMetric_delete',
    ),
    url(
        regex="^YearMetric/(?P<pk>\d+)/$",
        view=views.YearMetricDetailView.as_view(),
        name='YearMetric_detail',
    ),
    url(
        regex="^YearMetric/(?P<pk>\d+)/~update/$",
        view=views.YearMetricUpdateView.as_view(),
        name='YearMetric_update',
    ),
    url(
        regex="^YearMetric/$",
        view=views.YearMetricListView.as_view(),
        name='YearMetric_list',
    ),
	]
